### ISSUE TITLE
Natural spline basis matrix

### ISSUE THREAD

**Issue by nicklar** [ryantibs/dspline#5]
Hello,

Is it possible to construct the natural spline basis matrix (N_n) with this package? 

Thanks!

**Comment by ryantibs** [comment]
Hi @nicklar, do you mean the natural discrete basis from Section 7.3 of the paper (https://arxiv.org/pdf/2003.03886.pdf)? 

Unfortunately not, I haven't implemented that yet. Is this something you're looking to use for in an application of yours?

**Comment by nicklar** [comment]
@ryantibs yes it is - standard cubic splines perform badly for extrapolation so I am hoping to use natural splines to improve the behavior. I would be happy to share some examples of my specific code if that helps?

**Comment by ryantibs** [comment]
Sure feel free to post any examples here if you'd like. 

Just to be sure that you are in the right place---this is a repo for **discrete** splines, which are similar to, albeit not the same as splines. If you're looking for natural splines (not natural discrete splines) then there should be more standard tools available in R already.

**Comment by nicklar** [comment]
Yup I am interested in discrete splines specifically. I am using discrete splines to model discrete log concave probability distributions. This is fairly straightforward to do by solving a convex optimization problem (here I used CVXR). The issue with using discrete cubic splines is that the tails of the estimated pmf decay too fast. The fast decay in the tails that I am talking about is shown in the second figure. By using discrete **natural** cubic splines in the problem below I believe the extrapolation of the tails will be improved. 

`library('dspline')
library('CVXR')

### Fitting a discrete log concave spline to poisson data
n <- 40 # number of data points to sample
mu <- 20 # poisson mean
x_range <- 0:50
K <- max(x_range)
set.seed(1)

### sample poisson distribution and covert to counts
x_obs <- rpois(n, mu)
counts <- hist(x_obs, breaks = -1:K, right = TRUE, include.lowest = FALSE,
               plot = FALSE)$counts

### include knots at observations and construct spline basis
knot_idx = which(counts != 0)
Nt <- n_mat(3, x_range, knot_idx = knot_idx)

### set up and solve log concave spline convex optimization problem
alpha = Variable(length(knot_idx) + 3 + 1)
obj <- t (counts) %*% Nt %*%alpha # log likelihood
constraints <- list(sum(exp(Nt %*%alpha)) <= 1, 
                    diff((Nt %*%alpha)[1:K]) >= diff((Nt %*%alpha)[2:(K+1)]))
prob <- Problem(Maximize(obj), constraints) # maximize log likelihood
result <- solve(prob)

### plot the results (fig1)
plot(x_range, counts / sum(counts), xlab = 'counts', ylab = 'p')
lines(x_range, exp(Nt %*% result$getValue(alpha)), lty = 2)
lines(x_range, dpois(x_range, mu))
legend("topright",
       pch= c(NA, NA, 'o'), 
       lty = c(1, 2, NA),
       c("True PMF","Fit PMF", "Observed PMF"))
'
![fig1](https://user-images.githubusercontent.com/27034541/199232174-34ed1301-0cb0-4008-8339-bcdb1fdcd614.png)
'

### plot log probabilities (fig2)
plot(x_range, Nt %*% result$getValue(alpha), ylim = c(-100, 0), 
     xlab = 'counts', ylab = 'log(p)')
lines(x_range, log(dpois(x_range, mu)))
legend("bottomleft",
       pch= c(NA, 'o'),
       lty = c(1, NA),
       c("True PMF","Fit PMF"))
`
![fig2](https://user-images.githubusercontent.com/27034541/199232145-f435be5f-c4d9-4daa-87c3-a468a7aa4f62.png)

Hopefully this was clear. Curious to hear your thoughts on this - thanks for the help!

**Comment by ryantibs** [comment]
Thanks for sharing, this looks neat!

It's hard for me to grasp exactly what you're doing just based on the code (admittedly I'm only looking quickly) so if you have a quite latex writeup of your optimization problem it may help. A priori I don't know why the cubic tails would be responsible for the too-fast decay that you're seeing. The cubic tails will be high-variance, but I don't think they'd always be biased-down. Seems like it may be more of a consequence of the knot sequence you're specifying. What happens if you just expand the knot sequence a bit?

**Comment by nicklar** [comment]
I think you are right - the natural basis isn't necessary. I sent you an email with a latex write-up. Feel free to close this issue.
